# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
fi

# aliases for ls
alias lg='ls -l --group-directories-first'
alias lag='ls -lA --group-directories-first'

# aliases for git
alias gs='git status'
alias gd='git diff'
alias ga='git add'
alias gaa='git add .'
alias gl='git log'
alias glo='git log --oneline'
alias gb='git branch'
alias gc='git checkout'
alias gr='git remote'
alias gcmt='git commit -m'
alias grst='git reset'
alias gpll='git pull'
alias gpsh='git push'

# aliases for nvim
alias nv='nvim'

# aliases for python
alias python='python3'

# aliases for docker
alias dstt='sudo service docker start'
alias dstp='sudo service docker stop'
alias dcnt='docker container'
alias dimg='docker image'
alias dvlm='docker volume'
alias dntw='docker network'
alias dcmpup='docker-compose up -d'
alias dcmpdn='docker-compose down'
